import type { Exercise } from '../types/workout'

export const exercisesDB: Record<string, Exercise> = {
  EX001: {
    id: 'EX001',
    name: 'Supino Reto',
    description: 'Exercício composto para peitoral.',
    targetMuscles: ['Peitoral Maior', 'Tríceps', 'Deltoide Anterior'],
    executionNotes: 'Mantenha as escápulas retraídas e pés firmes no chão.',
    type: 'Compound',
  },
  EX002: {
    id: 'EX002',
    name: 'Remada Curvada',
    description: 'Exercício composto para costas.',
    targetMuscles: ['Latíssimo do Dorso', 'Romboides', 'Bíceps'],
    executionNotes: 'Mantenha a coluna neutra e puxe a barra na linha do umbigo.',
    type: 'Compound',
  },
  EX003: {
    id: 'EX003',
    name: 'Agachamento Livre',
    description: 'Exercício base para membros inferiores.',
    targetMuscles: ['Quadríceps', 'Glúteos', 'Isquiotibiais'],
    executionNotes: 'Mantenha o peito estufado e os joelhos alinhados com a ponta dos pés.',
    type: 'Compound',
  },
  EX004: {
    id: 'EX004',
    name: 'Levantamento Terra',
    description: 'Exercício composto de cadeia posterior.',
    targetMuscles: ['Isquiotibiais', 'Glúteos', 'Lombar'],
    executionNotes: 'A barra deve subir próxima às canelas, mantendo a coluna selada.',
    type: 'Compound',
  },
  EX005: {
    id: 'EX005',
    name: 'Desenvolvimento',
    description: 'Exercício para ombros.',
    targetMuscles: ['Deltoide Anterior', 'Deltoide Lateral', 'Tríceps'],
    executionNotes: 'Não curve excessivamente a lombar.',
    type: 'Compound',
  },
  EX006: {
    id: 'EX006',
    name: 'Puxada Frente',
    description: 'Exercício para a largura das costas.',
    targetMuscles: ['Latíssimo do Dorso', 'Bíceps'],
    executionNotes: 'Puxe a barra em direção à parte superior do peito.',
    type: 'Compound',
  },
  EX007: {
    id: 'EX007',
    name: 'Elevação Pélvica',
    description: 'Foco em ativação de glúteos.',
    targetMuscles: ['Glúteos', 'Isquiotibiais'],
    executionNotes: 'Aperte os glúteos no topo do movimento.',
    type: 'Isolation',
  },
  EX008: {
    id: 'EX008',
    name: 'Cadeira Extensora',
    description: 'Isolamento de quadríceps.',
    targetMuscles: ['Quadríceps'],
    executionNotes: 'Controle a fase excêntrica.',
    type: 'Isolation',
  },
  EX009: {
    id: 'EX009',
    name: 'Cadeira Flexora',
    description: 'Isolamento de isquiotibiais.',
    targetMuscles: ['Isquiotibiais'],
    executionNotes: 'Evite levantar o quadril do banco.',
    type: 'Isolation',
  },
  EX010: {
    id: 'EX010',
    name: 'Panturrilha em Pé',
    description: 'Exercício para panturrilhas.',
    targetMuscles: ['Gastrocnêmio'],
    executionNotes: 'Realize o movimento completo de alongamento e contração.',
    type: 'Isolation',
  },
  EX011: {
    id: 'EX011',
    name: 'Rosca Direta',
    description: 'Exercício para bíceps.',
    targetMuscles: ['Bíceps Braquial'],
    executionNotes: 'Mantenha os cotovelos fixos ao lado do corpo.',
    type: 'Isolation',
  },
  EX012: {
    id: 'EX012',
    name: 'Tríceps Pulley',
    description: 'Exercício para tríceps.',
    targetMuscles: ['Tríceps Braquial'],
    executionNotes: 'Estenda totalmente os cotovelos sem mover os ombros.',
    type: 'Isolation',
  },
  EX013: {
    id: 'EX013',
    name: 'Face Pull',
    description: 'Corretivo para postura dos ombros.',
    targetMuscles: ['Deltoide Posterior', 'Romboides', 'Manguito Rotador'],
    executionNotes: 'Puxe a corda na direção do rosto, rotacionando externamente.',
    type: 'Isolation',
  },
  EX014: {
    id: 'EX014',
    name: 'Crucifixo Inverso',
    description: 'Foco na parte posterior do ombro.',
    targetMuscles: ['Deltoide Posterior'],
    executionNotes: 'Concentre o movimento nas escápulas.',
    type: 'Isolation',
  },
  EX015: {
    id: 'EX015',
    name: 'Encolhimento',
    description: 'Foco no trapézio superior.',
    targetMuscles: ['Trapézio Superior'],
    executionNotes: 'Eleve os ombros em direção às orelhas e segure por 1 segundo.',
    type: 'Isolation',
  },
  EX016: {
    id: 'EX016',
    name: 'Prancha Abdominal',
    description: 'Estabilização do core.',
    targetMuscles: ['Transverso do Abdômen', 'Core'],
    executionNotes: 'Mantenha o corpo alinhado, contraindo o abdômen e glúteos.',
    type: 'Compound',
  },
  EX017: {
    id: 'EX017',
    name: 'Abdominal Supra',
    description: 'Foco no reto abdominal.',
    targetMuscles: ['Reto Abdominal'],
    executionNotes: 'Suba o tronco apenas tirando as escápulas do chão.',
    type: 'Isolation',
  },
  EX018: {
    id: 'EX018',
    name: 'Alongamento de Peitoral',
    description: 'Aumento de flexibilidade.',
    targetMuscles: ['Peitoral Maior', 'Peitoral Menor'],
    executionNotes: 'Apoie o braço em uma porta e gire o tronco suavemente.',
    type: 'Mobility',
  },
  EX019: {
    id: 'EX019',
    name: 'Alongamento Flexores de Quadril',
    description: 'Melhora da mobilidade pélvica.',
    targetMuscles: ['Iliopsoas', 'Reto Femoral'],
    executionNotes: 'Apoie um joelho no chão e avance o quadril sem arquear a lombar.',
    type: 'Mobility',
  },
  EX020: {
    id: 'EX020',
    name: 'Chin Tucks',
    description: 'Retração cervical.',
    targetMuscles: ['Flexores Profundos do Pescoço'],
    executionNotes: 'Puxe o queixo para trás como se fosse fazer um "queixo duplo".',
    type: 'Mobility',
  },
  EX021: {
    id: 'EX021',
    name: 'Mobilidade Torácica',
    description: 'Extensão da coluna torácica.',
    targetMuscles: ['Eretores da Espinha'],
    executionNotes: 'Use um rolo de espuma no meio das costas e estenda.',
    type: 'Mobility',
  },
  EX022: {
    id: 'EX022',
    name: 'Elevação Lateral',
    description: 'Exercício para ombros.',
    targetMuscles: ['Deltoide Lateral'],
    executionNotes: 'Eleve os braços até a linha dos ombros.',
    type: 'Isolation',
  },
  EX023: {
    id: 'EX023',
    name: 'Stiff',
    description: 'Exercício para cadeia posterior.',
    targetMuscles: ['Isquiotibiais', 'Glúteos'],
    executionNotes: 'Mantenha as pernas semi-estendidas e coluna neutra.',
    type: 'Compound',
  },
  EX024: {
    id: 'EX024',
    name: 'Cadeira Abdutora',
    description: 'Trabalho de glúteo médio.',
    targetMuscles: ['Glúteo Médio', 'Abdutores'],
    executionNotes: 'Apoie bem as costas e realize a abdução controlada.',
    type: 'Isolation',
  },
  EX025: {
    id: 'EX025',
    name: 'Cadeira Adutora',
    description: 'Trabalho de adutores de coxa.',
    targetMuscles: ['Adutores'],
    executionNotes: 'Feche as pernas controlando o movimento de volta.',
    type: 'Isolation',
  },
  EX026: {
    id: 'EX026',
    name: 'Esteira',
    description: 'Cardio de baixa intensidade.',
    targetMuscles: ['Cardio'],
    executionNotes: 'Mantenha um ritmo constante que permita conversar.',
    type: 'Cardio',
  },
  EX027: {
    id: 'EX027',
    name: 'Bicicleta Ergométrica',
    description: 'Cardio sem impacto.',
    targetMuscles: ['Cardio', 'Quadríceps'],
    executionNotes: 'Ajuste o banco na altura do quadril.',
    type: 'Cardio',
  },
}

export const deviationMappings: Record<
  string,
  { exerciseId: string; priority: number; efficacy: number }[]
> = {
  DE001: [
    { exerciseId: 'EX020', priority: 1, efficacy: 0.95 },
    { exerciseId: 'EX013', priority: 2, efficacy: 0.85 },
    { exerciseId: 'EX018', priority: 3, efficacy: 0.8 },
  ],
  DE002: [
    { exerciseId: 'EX021', priority: 1, efficacy: 0.95 },
    { exerciseId: 'EX013', priority: 2, efficacy: 0.9 },
    { exerciseId: 'EX002', priority: 3, efficacy: 0.85 },
  ],
  DE003: [
    { exerciseId: 'EX019', priority: 1, efficacy: 0.95 },
    { exerciseId: 'EX016', priority: 2, efficacy: 0.9 },
    { exerciseId: 'EX007', priority: 3, efficacy: 0.85 },
  ],
  DE004: [
    { exerciseId: 'EX023', priority: 1, efficacy: 0.85 },
    { exerciseId: 'EX004', priority: 2, efficacy: 0.8 },
  ],
  DE005: [{ exerciseId: 'EX016', priority: 1, efficacy: 0.85 }],
  DE006: [
    { exerciseId: 'EX014', priority: 1, efficacy: 0.95 },
    { exerciseId: 'EX018', priority: 2, efficacy: 0.9 },
  ],
  DE007: [
    { exerciseId: 'EX024', priority: 1, efficacy: 0.95 },
    { exerciseId: 'EX007', priority: 2, efficacy: 0.85 },
  ],
}

export const prohibitedMappings: Record<string, string[]> = {
  DE001: ['EX005'],
  DE004: ['EX004', 'EX003'],
  DE006: ['EX001'],
}
